import type { Metadata } from "next";
import { Inria_Sans, Inria_Serif } from "next/font/google";
import "./globals.css";

export const inriaSans = Inria_Sans({ weight: "400", subsets: ["latin"], variable: "--font-inria_sans" });
export const inriaSerif = Inria_Serif({ weight: "300", subsets: ["latin"], variable: "--font-inria_serif" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inriaSerif.variable} ${inriaSans.variable}`}>{children}</body>
    </html>
  );
}
